#!/bin/sh

docker build --no-cache -f IPS4/php7/Dockerfile -t $DOCKER_REPO:7-apache-ips-4 .
docker build --no-cache -f IPS4/php8/Dockerfile -t $DOCKER_REPO:8-apache-ips-4 .
docker build --no-cache -f phpBB3/php7/Dockerfile -t $DOCKER_REPO:7-apache-phpbb-3 .
docker build --no-cache -f phpBB3/php8/Dockerfile -t $DOCKER_REPO:8-apache-phpbb-3 .
